version: "3.8"
services:
  thirdparty:
    build: ./thirdpartymock
    ports:
      - "3000:3000"

  client:
    build: ./client
    environment:
      YOUR_API: "http://transaction-service:3300" # replace with your new API
    ports:
      - "3100:3100"

  transaction-service:
    build: ./transaction-service
    ports:
      - "3300:3300"
    env_file:
      - ./transaction-service/.env
